{
 "title": "Qnap",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_cpuID",
     "groupBy": [
      { "params": [ "20s" ], "type": "time" },
      { "params": [ "cpuID" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp.QNAP.cpuTable",
     "select": [
      [
       { "params": [ "cpuUsage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Available MEM",
     "groupBy": [
      { "params": [ "20s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp.QNAP.systemTable",
     "select": [
      [
       { "params": [ "systemFreeMemEX" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " * 1000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "System Fan Speed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "RPM" }
   ],
   "targets": [
    {
     "alias": "$tag_sysFanDescrEX",
     "groupBy": [
      { "params": [ "20s" ], "type": "time" },
      { "params": [ "sysFanDescrEX" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp.QNAP.systemFanTableEx",
     "select": [
      [
       { "params": [ "sysFanSpeedEX" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Enclosure temp",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "$tag_enclosureModel",
     "groupBy": [
      { "params": [ "20s" ], "type": "time" },
      { "params": [ "enclosureModel" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp.QNAP.enclosureTable",
     "select": [
      [
       { "params": [ "enclosureSystemTemp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_ifName RX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ifName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp.QNAP.ifXTable",
     "select": [
      [
       { "params": [ "ifHCInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" },
       { "params": [ "RX" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "ifName", "operator": "=", "value": "eth0" },
      { "condition": "OR", "key": "ifName", "operator": "=", "value": "eth1" }
     ]
    },
    {
     "alias": "$tag_ifName TX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ifName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp.QNAP.ifXTable",
     "select": [
      [
       { "params": [ "ifHCOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" },
       { "params": [ "RX" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "ifName", "operator": "=", "value": "eth0" },
      { "condition": "OR", "key": "ifName", "operator": "=", "value": "eth1" }
     ]
    }
   ]
  },
  { "title": "Disks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Disk Temperatures 10TB",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "$tag_diskModel $tag_diskID $col",
     "groupBy": [
      { "params": [ "20s" ], "type": "time" },
      { "params": [ "diskID" ], "type": "tag" },
      { "params": [ "diskModel" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp.QNAP.diskTable",
     "select": [
      [
       { "params": [ "diskTemperture" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "diskModel",
       "operator": "=",
       "value": "Seagate ST10000VN0004-1ZD101 (SATA)"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk Temperatures 12TB",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "$tag_diskModel $tag_diskID $col",
     "groupBy": [
      { "params": [ "20s" ], "type": "time" },
      { "params": [ "diskID" ], "type": "tag" },
      { "params": [ "diskModel" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp.QNAP.diskTable",
     "select": [
      [
       { "params": [ "diskTemperture" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "diskModel",
       "operator": "=",
       "value": "Seagate ST12000VN0007-2GS116 (SATA)"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk Temperatures SSD",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "$tag_diskModel $tag_diskID $col",
     "groupBy": [
      { "params": [ "20s" ], "type": "time" },
      { "params": [ "diskID" ], "type": "tag" },
      { "params": [ "diskModel" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp.QNAP.diskTable",
     "select": [
      [
       { "params": [ "diskTemperture" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "diskModel", "operator": "=", "value": "Samsung SSD 850 EVO 1TB (SATA)" }
     ]
    }
   ]
  },
  {
   "title": "Free Disk Space",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_sysVolumeDescrEX",
     "groupBy": [
      { "params": [ "20s" ], "type": "time" },
      { "params": [ "sysVolumeDescrEX" ], "type": "tag" }
     ],
     "measurement": "snmp.QNAP.systemVolumeTableEx",
     "select": [
      [
       { "params": [ "sysVolumeFreeSize" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "alias": "12x10TB RAID6 HDD",
     "groupBy": [
      { "params": [ "20s" ], "type": "time" },
      { "params": [ "blvID" ], "type": "tag" }
     ],
     "measurement": "snmp.QNAP.diskPerformanceTable",
     "select": [
      [
       { "params": [ "iops" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "blvID", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "4x1TB RAID5 SSD",
     "groupBy": [
      { "params": [ "20s" ], "type": "time" },
      { "params": [ "blvID" ], "type": "tag" }
     ],
     "measurement": "snmp.QNAP.diskPerformanceTable",
     "select": [
      [
       { "params": [ "iops" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "blvID", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "10x12TB RAID6 HDD",
     "groupBy": [
      { "params": [ "20s" ], "type": "time" },
      { "params": [ "blvID" ], "type": "tag" }
     ],
     "measurement": "snmp.QNAP.diskPerformanceTable",
     "select": [
      [
       { "params": [ "iops" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "blvID", "operator": "=", "value": "3" }
     ]
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "12x10TB RAID6 HDD",
     "groupBy": [
      { "params": [ "20s" ], "type": "time" },
      { "params": [ "blvID" ], "type": "tag" }
     ],
     "measurement": "snmp.QNAP.diskPerformanceTable",
     "select": [
      [
       { "params": [ "latency" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "blvID", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "4x1TB RAID5 SSD",
     "groupBy": [
      { "params": [ "20s" ], "type": "time" },
      { "params": [ "blvID" ], "type": "tag" }
     ],
     "measurement": "snmp.QNAP.diskPerformanceTable",
     "select": [
      [
       { "params": [ "latency" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "blvID", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "10x12TB RAID6 HDD",
     "groupBy": [
      { "params": [ "20s" ], "type": "time" },
      { "params": [ "blvID" ], "type": "tag" }
     ],
     "measurement": "snmp.QNAP.diskPerformanceTable",
     "select": [
      [
       { "params": [ "latency" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "blvID", "operator": "=", "value": "3" }
     ]
    }
   ]
  }
 ]
}